language: erlang
otp_release:
  - 19.2
  - 18.1
  - 17.4
  - R16B03
script:
  - ./rebar3 dialyzer
  - ./rebar3 xref
  - ./rebar3 eunit
notifications:
  email: christopher.meiklejohn@gmail.com
sudo: false
